#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Information
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="baguio_db")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertstudent_info(student_info instance);
    partial void Updatestudent_info(student_info instance);
    partial void Deletestudent_info(student_info instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Information.Properties.Settings.Default.baguio_dbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<student_info> student_infos
		{
			get
			{
				return this.GetTable<student_info>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.info_delete")]
		public int info_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> auto_tbl_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), auto_tbl_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.info_save")]
		public int info_save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stud_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string stud_lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string stud_fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> stud_midinit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] string stud_contact_no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), stud_id, stud_lname, stud_fname, stud_midinit, stud_contact_no);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.info_search")]
		public ISingleResult<info_searchResult> info_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<info_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.info_update")]
		public int info_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> auto_tbl_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stud_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string stud_lname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string stud_fname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> stud_midnit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(13)")] string stud_contact_no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), auto_tbl_id, stud_id, stud_lname, stud_fname, stud_midnit, stud_contact_no);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.info_view")]
		public ISingleResult<info_viewResult> info_view()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<info_viewResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.student_info")]
	public partial class student_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _auto_tbl_id;
		
		private System.Nullable<int> _stud_id;
		
		private string _stud_lname;
		
		private string _stud_fname;
		
		private System.Nullable<char> _stud_midnit;
		
		private string _stud_contact_no;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onauto_tbl_idChanging(int value);
    partial void Onauto_tbl_idChanged();
    partial void Onstud_idChanging(System.Nullable<int> value);
    partial void Onstud_idChanged();
    partial void Onstud_lnameChanging(string value);
    partial void Onstud_lnameChanged();
    partial void Onstud_fnameChanging(string value);
    partial void Onstud_fnameChanged();
    partial void Onstud_midnitChanging(System.Nullable<char> value);
    partial void Onstud_midnitChanged();
    partial void Onstud_contact_noChanging(string value);
    partial void Onstud_contact_noChanged();
    #endregion
		
		public student_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auto_tbl_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int auto_tbl_id
		{
			get
			{
				return this._auto_tbl_id;
			}
			set
			{
				if ((this._auto_tbl_id != value))
				{
					this.Onauto_tbl_idChanging(value);
					this.SendPropertyChanging();
					this._auto_tbl_id = value;
					this.SendPropertyChanged("auto_tbl_id");
					this.Onauto_tbl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_id", DbType="Int")]
		public System.Nullable<int> stud_id
		{
			get
			{
				return this._stud_id;
			}
			set
			{
				if ((this._stud_id != value))
				{
					this.Onstud_idChanging(value);
					this.SendPropertyChanging();
					this._stud_id = value;
					this.SendPropertyChanged("stud_id");
					this.Onstud_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_lname", DbType="VarChar(50)")]
		public string stud_lname
		{
			get
			{
				return this._stud_lname;
			}
			set
			{
				if ((this._stud_lname != value))
				{
					this.Onstud_lnameChanging(value);
					this.SendPropertyChanging();
					this._stud_lname = value;
					this.SendPropertyChanged("stud_lname");
					this.Onstud_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_fname", DbType="VarChar(50)")]
		public string stud_fname
		{
			get
			{
				return this._stud_fname;
			}
			set
			{
				if ((this._stud_fname != value))
				{
					this.Onstud_fnameChanging(value);
					this.SendPropertyChanging();
					this._stud_fname = value;
					this.SendPropertyChanged("stud_fname");
					this.Onstud_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_midnit", DbType="Char(1)")]
		public System.Nullable<char> stud_midnit
		{
			get
			{
				return this._stud_midnit;
			}
			set
			{
				if ((this._stud_midnit != value))
				{
					this.Onstud_midnitChanging(value);
					this.SendPropertyChanging();
					this._stud_midnit = value;
					this.SendPropertyChanged("stud_midnit");
					this.Onstud_midnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_contact_no", DbType="VarChar(13)")]
		public string stud_contact_no
		{
			get
			{
				return this._stud_contact_no;
			}
			set
			{
				if ((this._stud_contact_no != value))
				{
					this.Onstud_contact_noChanging(value);
					this.SendPropertyChanging();
					this._stud_contact_no = value;
					this.SendPropertyChanged("stud_contact_no");
					this.Onstud_contact_noChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class info_searchResult
	{
		
		private System.Nullable<int> _stud_id;
		
		private string _stud_lname;
		
		private string _stud_fname;
		
		private System.Nullable<char> _stud_midnit;
		
		private string _stud_contact_no;
		
		public info_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_id", DbType="Int")]
		public System.Nullable<int> stud_id
		{
			get
			{
				return this._stud_id;
			}
			set
			{
				if ((this._stud_id != value))
				{
					this._stud_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_lname", DbType="VarChar(50)")]
		public string stud_lname
		{
			get
			{
				return this._stud_lname;
			}
			set
			{
				if ((this._stud_lname != value))
				{
					this._stud_lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_fname", DbType="VarChar(50)")]
		public string stud_fname
		{
			get
			{
				return this._stud_fname;
			}
			set
			{
				if ((this._stud_fname != value))
				{
					this._stud_fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_midnit", DbType="Char(1)")]
		public System.Nullable<char> stud_midnit
		{
			get
			{
				return this._stud_midnit;
			}
			set
			{
				if ((this._stud_midnit != value))
				{
					this._stud_midnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_contact_no", DbType="VarChar(13)")]
		public string stud_contact_no
		{
			get
			{
				return this._stud_contact_no;
			}
			set
			{
				if ((this._stud_contact_no != value))
				{
					this._stud_contact_no = value;
				}
			}
		}
	}
	
	public partial class info_viewResult
	{
		
		private System.Nullable<int> _stud_id;
		
		private string _stud_lname;
		
		private string _stud_fname;
		
		private System.Nullable<char> _stud_midnit;
		
		private string _stud_contact_no;
		
		private int _auto_tbl_id;
		
		public info_viewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_id", DbType="Int")]
		public System.Nullable<int> stud_id
		{
			get
			{
				return this._stud_id;
			}
			set
			{
				if ((this._stud_id != value))
				{
					this._stud_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_lname", DbType="VarChar(50)")]
		public string stud_lname
		{
			get
			{
				return this._stud_lname;
			}
			set
			{
				if ((this._stud_lname != value))
				{
					this._stud_lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_fname", DbType="VarChar(50)")]
		public string stud_fname
		{
			get
			{
				return this._stud_fname;
			}
			set
			{
				if ((this._stud_fname != value))
				{
					this._stud_fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_midnit", DbType="Char(1)")]
		public System.Nullable<char> stud_midnit
		{
			get
			{
				return this._stud_midnit;
			}
			set
			{
				if ((this._stud_midnit != value))
				{
					this._stud_midnit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_contact_no", DbType="VarChar(13)")]
		public string stud_contact_no
		{
			get
			{
				return this._stud_contact_no;
			}
			set
			{
				if ((this._stud_contact_no != value))
				{
					this._stud_contact_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auto_tbl_id", DbType="Int NOT NULL")]
		public int auto_tbl_id
		{
			get
			{
				return this._auto_tbl_id;
			}
			set
			{
				if ((this._auto_tbl_id != value))
				{
					this._auto_tbl_id = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
